# Generated by Django 6.0 on 2025-12-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_is_active_and_more'),
        ('leave', '0002_leave_employee_name_leave_end_date_leave_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
