from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['title', 'report_type', 'description', 'report_date', 'generated_by']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Report Title'}),
            'report_type': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description', 'rows': 4}),
            'report_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'generated_by': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Generated By'}),
        }
