# Generated by Django 6.0 on 2025-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitment_applied_date_recruitment_candidate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='employee_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('hired', 'Hired ✓')], default='open', max_length=20),
        ),
    ]
