# Generated by Django 6.0 on 2025-12-17 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='employee_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='performance',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='performance',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
