# Generated by Django 6.0 on 2025-12-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_is_active_and_more'),
        ('performance', '0002_performance_employee_name_performance_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
