# Generated by Django 6.0 on 2025-12-17 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('attendance', 'Attendance Report'), ('payroll', 'Payroll Report'), ('performance', 'Performance Report'), ('recruitment', 'Recruitment Report')], default='attendance', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Report', max_length=200),
        ),
    ]
