# Generated by Django 6.0 on 2025-12-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_is_active_and_more'),
        ('task', '0002_task_assigned_to_task_description_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='For single assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(choices=[('single', 'Single Employee'), ('team', 'Team'), ('admin', 'Admin')], default='single', max_length=20),
        ),
    ]
